# AWS SAM template

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: S3 Asset Transformer

Parameters:
  TransformationKeyPrefix:
    Type: String
    Default: '_/'
    AllowedValues:
      - '_/'
    Description: >
      When uploading to this bucket, any objects which are prefixed with this key will be transformed. This prefix is
      deliberately very short. For scenarios where the bucket is experience very high requests load, the beginning of the key
      should be as unique as possible.
      see: https://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html?shortFooter=true#workloads-with-mix-request-types
  NewBucketName:
    Type: String
    Default: 'my-unique-bucket-name-298043'
    Description: >
      The name of the new bucket which will be created. Must be a valid bucket name and unique in the AWS Universe
Resources:
  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_contents
      MemorySize: 512
      Environment:
        Variables:
          TRANSFORMATION_KEY_PREFIX:
            Ref: TransformationKeyPrefix
      Policies:
        - Version: '2012-10-17'
          Statement: # Permission to lambda to read from "Processing Bucket"
            - Effect: Allow
              Action: # TODO restrict to only actions and buckets as required
                - 's3:*'
              Resource: !Sub 'arn:aws:s3:::${NewBucketName}*'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: TransformerBucket
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value:
                      Ref: TransformationKeyPrefix
  TransformerBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: NewBucketName

